version: 2.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: typelead/eta:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - dot-eta-{{ checksum "kafka-admin-rest.cabal" }}
            - dot-eta

      - restore_cache:
          keys:
            - dist-{{ checksum "kafka-admin-rest.cabal" }}
            - dist

      - run: etlas update
      - run: etlas install --dependencies-only
      - run: etlas configure --enable-uberjar-mode
      - run: etlas build

      - save_cache:
          key: dot-eta
          paths:
            - ~/.eta
            - ~/.etlas
            - ~/.coursier

      - save_cache:
          key: dot-eta-{{ checksum "kafka-admin-rest.cabal" }}
          paths:
            - ~/.eta
            - ~/.etlas
            - ~/.coursier

      - save_cache:
          key: dist
          paths:
            - ./dist

      - save_cache:
          key: dist-{{ checksum "kafka-admin-rest.cabal" }}
          paths:
            - ./dist

      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build the container
          command: ./scripts/container.sh build

      - deploy:
          name: Pushing container
          command: ./scripts/container.sh push